# Find protocol version numbers here:
# https://minecraft.fandom.com/wiki/Protocol_version#List_of_protocol_versions
# Leave whitelist empty to allow all versions

messagePrefix: "<dark_gray>[</dark_gray><aqua>ForceVersion</aqua><dark_gray>]</dark_gray> "

global:
  versionWhitelist: [757, 758, 759, 760, 761]
  versionBlacklist: []
  kickMessage: "Outdated client, please use Minecraft 1.18-1.19.3"

# Protocol version and name for when players don't have an allowed version
# This currently only works when using a proxy
serverPing:
  version: 761
  # Version name that will be shown in red text in the server browser, leave blank for default
  versionName: "1.18-1.19.3"

# Add rules for as many servers as you want
# Servers without rules will use the global rules
servers:
  # Here are some examples to get you started
  example-server:
    versionWhitelist: [761]
    versionBlacklist: []
    kickMessage: "This server only supports 1.19.3"
  example-server-2:
    versionWhitelist: []
    versionBlacklist: [757, 758]
    kickMessage: "<red>Example 2 isn't available for Minecraft 1.18.X, please use 1.19-1.19.3</red>"